---
- name: Check if sudo is installed.
  command: dpkg-query -l sudo
  register: sudo_installed_result
  # dpkg returns 1 if package not found,
  # so disable the scary red text by setting no-fail mode.
  # The output from the command is checked in the next task.
  failed_when: false
  changed_when: false
  # Necessary to support --check mode
  always_run: true

- name: Install sudo.
  apt:
    name: sudo
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: "'no packages found' in sudo_installed_result.stderr"

