---
- name: download...
  get_url: >-
    url={{kibana_tgz_url}}
    dest=/tmp/{{kibana_tgz}}
    owner=root
    group=root
    mode=0644
  sudo: true

- name: unarchive...
  unarchive: >-
    copy=no
    src=/tmp/{{kibana_tgz}}
    dest=/opt
    owner=root
    group=root
    creates=/opt/{{kibana_name}}
  sudo: true

- name: Creates directory
  sudo: true
  file: path=/var/www/kibana3/ state=directory

- name: copy files
  sudo: true
  shell: cp -r /opt/{{kibana_name}}/* /var/www/kibana3/

  
    
